return {
  {
    'miversen33/sunglasses.nvim',
    config = {
      -- SHADE, TINT, NOSYNTAX
      filter_type = 'SHADE',
      filter_percent = 0.55,
      excluded_filetypes = {
        'dashboard',
        'lspsagafinder',
        'packer',
        'checkhealth',
        'mason',
        'NvimTree',
        'neo-tree',
        'plugin',
        'lazy',
        'TelescopePrompt',
        'alpha',
        'toggleterm',
        'sagafinder',
        'better_term',
        'fugitiveblame',
        'starter',
        'NeogitPopup',
        'NeogitStatus',
        'DiffviewFiles',
        'DiffviewFileHistory',
        'DressingInput',
        'spectre_panel',
        'zsh',
        'registers',
        'startuptime',
        'OverseerList',
        'Outline',
        'Navbuddy',
        'noice',
        'notify',
        'saga_codeaction',
        'sagarename',
      },
    },
    event = 'UIEnter',
    vim.keymap.set('n', '<C-s>', ':SunglassesEnableToggle <CR>', { desc = 'Sunglasses Toggle' }),
  },
}
